In [1]:
] add CSV

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


In [2]:
] add DataFrames

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


In [3]:
using CSV

In [4]:
using DataFrames

In [6]:
alldata = CSV.read("data.csv", DataFrame)

20×6 DataFrame
 Row │ row    x      y      sigma_y  sigma_x  rho_xy  
     │ Int64  Int64  Int64  Int64    Int64    Float64 
─────┼────────────────────────────────────────────────
   1 │     1    201    592       61        9    -0.84
   2 │     2    244    401       25        4     0.31
   3 │     3     47    583       38       11     0.64
   4 │     4    287    402       15        7    -0.27
   5 │     5    203    495       21        5    -0.33
   6 │     6     58    173       15        9     0.67
   7 │     7    210    479       27        4    -0.02
   8 │     8    202    504       14        4    -0.05
   9 │     9    198    510       30       11    -0.84
  10 │    10    158    416       16        7    -0.69
  11 │    11    165    393       14        5     0.3
  12 │    12    201    442       25        5    -0.46
  13 │    13    157    317       52        5    -0.03
  14 │    14    131    311       16        6     0.5
  15 │    15    166    400       34        6     0.73
  16 │    16    160    337       31        5    -0.52
  17 │    17    186    423       42        9     0.9
  18 │    18    125    334       26        8     0.4
  19 │    19    218    533       16        6    -0.78
  20 │    20    146    344       22        5    -0.56

In [7]:
alldata.x

20-element Vector{Int64}:
 201
 244
  47
 287
 203
  58
 210
 202
 198
 158
 165
 201
 157
 131
 166
 160
 186
 125
 218
 146

In [8]:
size(alldata)

(20, 6)

In [9]:
size(alldata,1)

20

In [10]:
data = alldata[5:end, :]

16×6 DataFrame
 Row │ row    x      y      sigma_y  sigma_x  rho_xy  
     │ Int64  Int64  Int64  Int64    Int64    Float64 
─────┼────────────────────────────────────────────────
   1 │     5    203    495       21        5    -0.33
   2 │     6     58    173       15        9     0.67
   3 │     7    210    479       27        4    -0.02
   4 │     8    202    504       14        4    -0.05
   5 │     9    198    510       30       11    -0.84
   6 │    10    158    416       16        7    -0.69
   7 │    11    165    393       14        5     0.3
   8 │    12    201    442       25        5    -0.46
   9 │    13    157    317       52        5    -0.03
  10 │    14    131    311       16        6     0.5
  11 │    15    166    400       34        6     0.73
  12 │    16    160    337       31        5    -0.52
  13 │    17    186    423       42        9     0.9
  14 │    18    125    334       26        8     0.4
  15 │    19    218    533       16        6    -0.78
  16 │    20    146    344       22        5    -0.56

In [11]:
data[begin:2,:]

2×6 DataFrame
 Row │ row    x      y      sigma_y  sigma_x  rho_xy  
     │ Int64  Int64  Int64  Int64    Int64    Float64 
─────┼────────────────────────────────────────────────
   1 │     5    203    495       21        5    -0.33
   2 │     6     58    173       15        9     0.67

In [12]:
using WGLMakie

Large amount of data should be stored in hdf data format 

In [13]:
f = Figure()
Axis(f[1, 1])
errorbars!(data.x, data.y, data.sigma_y)
scatter!(data.x, data.y, markersize = 10, color = :black) # this automatically create hold on module 
# super efficient string is the colon before the black (need to search about it)
f

In [14]:
m = 2;
b = 100;

In [15]:
xx = LinRange(50, 250, 25);

In [16]:
f = Figure()
Axis(f[1, 1])
errorbars!(data.x, data.y, data.sigma_y)
scatter!(data.x, data.y, markersize = 10, color = :black)
yy = m .*xx .+ b
lines!(xx, yy)
f

In [17]:
] add Optim

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


In [18]:
using Optim

Objective function over and over again to find the proper location 

In [19]:
function abs_diff(x, mean)
    return sum(abs.(x .- mean))
end

abs_diff (generic function with 1 method)

In [20]:
function line_abs_diff(x, b, m, y)
    y_pred = b .+ x .* m
    return abs_diff(y_pred, y)
end

line_abs_diff (generic function with 1 method)

In [21]:
function objective_abs(params)
    b = params[1]
    m = params[2]
    @show b, m # this macro is very useful for doing 
    return line_abs_diff(data.x, b, m, data.y) # the output for this function
    # to be a single valued in order for it to be a single data
end

objective_abs (generic function with 1 method)

In [22]:
result = optimize(objective_abs, [b,m] .+ 0.) # the floating point array also works for this problem
# here Justin did type casting to float64
# the second argument is for the starting parameters

(b, m) = (100.0, 2.0)
(b, m) = (150.025, 2.0)
(b, m) = (100.0, 3.025)
(b, m) = (150.025, 0.9750000000000001)
(b, m) = (137.51875, 1.4875)
(b, m) = (87.49375, 1.4874999999999998)
(b, m) = (103.1265625, 1.6156249999999999)
(b, m) = (134.3921875, 1.871875)
(b, m) = (110.94296875, 1.6796875)
(b, m) = (148.46171875000002, 1.1671874999999998)
(b, m) = (112.11542968750001, 1.791796875)
(b, m) = (85.5396484375, 1.9839843750000001)
(b, m) = (59.55009765625, 2.2322265625)
(b, m) = (84.3671875, 1.8718750000000004)
(b, m) = (70.49306640625, 1.9119140625000006)
(b, m) = (58.9638671875, 2.1761718750000005)
(b, m) = (57.791406249999994, 2.0640625000000004)
(b, m) = (43.91728515624999, 2.1041015625000004)
(b, m) = (69.32060546874999, 1.7998046875)
(b, m) = (61.5530517578125, 2.082080078125)
(b, m) = (21.103149414062486, 2.3143066406250004)
(b, m) = (3.4673828124999773, 2.3363281250000005)
(b, m) = (17.988800048828107, 2.2727661132812504)
(b, m) = (40.802935791015614, 2.06256103515625)
(b, m) = (26.028

 * Status: success

 * Candidate solution
    Final objective value:     3.765701e+02

 * Found with
    Algorithm:     Nelder-Mead

 * Convergence measures
    √(Σ(yᵢ-ȳ)²)/n ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    97
    f(x) calls:    191


In [23]:
b_abs,m_abs = Optim.minimizer(result) # this function will output the optimized value

2-element Vector{Float64}:
 53.7476634864048
  2.0560747668648753

In [24]:
f = Figure()
Axis(f[1, 1])
errorbars!(data.x, data.y, data.sigma_y)
scatter!(data.x, data.y, markersize = 10, color = :black)
lines!(xx, b_abs .+ m_abs .* xx)
f

In [25]:
function gaussian_log_likelihood(x, mean, sigma)
    return sum(-log.(sigma * sqrt(2*π)) - 0.5 * (x - mean).^2 ./ sigma.^2)
end

gaussian_log_likelihood (generic function with 1 method)

In [26]:
gaussian_log_likelihood(data.y, m .* data.x .+ b, data.sigma_y)

-90.96079216076429

In [27]:
function objective(params)
    b = params[1]
    m = params[2]
    y_pred = b .+ m .* data.x
    return -gaussian_log_likelihood(data.y .+ 0., y_pred, data.sigma_y .+ 0.)
end

objective (generic function with 1 method)

In [28]:
[b,m].+0.

2-element Vector{Float64}:
 100.0
   2.0

In [34]:
result = optimize(objective, [b,m] .+ 0.)

 * Status: success

 * Candidate solution
    Final objective value:     7.430617e+01

 * Found with
    Algorithm:     Nelder-Mead

 * Convergence measures
    √(Σ(yᵢ-ȳ)²)/n ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    41
    f(x) calls:    81


In [29]:
b_opt,m_opt = Optim.minimizer(result)

2-element Vector{Float64}:
 53.7476634864048
  2.0560747668648753

In [30]:
function objective_2(x, b, m, y, sigma_y)
    y_pred = b .+ m .* x
    return -gaussian_log_likelihood(y, y_pred, sigma_y)
end

objective_2 (generic function with 1 method)

In [31]:
result = optimize(p -> objective_2(data.x, p[1], p[2], data.y, data.sigma_y),
                  [b,m] .+ 0.);
Optim.converged(result)

true

In [32]:
b_opt,m_opt = Optim.minimizer(result)

2-element Vector{Float64}:
 34.05070589633283
  2.2399054546066215

In [33]:
f = Figure()
Axis(f[1, 1])
errorbars!(data.x, data.y, data.sigma_y)
scatter!(data.x, data.y, markersize = 10, color = :black)
lines!(xx, b_opt .+ m_opt .* xx, )
lines!(xx, b_abs .+ m_abs .* xx, color=:red)
f

In [34]:
append!([1,2],[3,4])

4-element Vector{Int64}:
 1
 2
 3
 4

In [36]:
data.x[1:0]
@show data.x; # only $data.x command will just dump the output

data.x = [203, 58, 210, 202, 198, 158, 165, 201, 157, 131, 166, 160, 186, 125, 218, 146]


In [37]:
# This process is called the jackknife method
n = length(data.x)

B_jack = zeros(n)
M_jack = zeros(n)

for i in 1:n
    x_sub = append!(data.x[1:(i-1)], data.x[(i+1):n]) # deleteat!(data.x, i),  Erick with the magic !!
    y_sub = append!(data.y[1:(i-1)], data.y[(i+1):n])
    s_sub = append!(data.sigma_y[1:(i-1)], data.sigma_y[(i+1):n])
    result = optimize(p -> objective_2(x_sub, p[1], p[2], y_sub, s_sub),
                      [b,m] .+ 0.); # anonymous function definition 
                                    # this grabs the global function at the -> result
    @assert(Optim.converged(result)) #@assert wiil evaluate the result is true of false
    b,m = Optim.minimizer(result)
    B_jack[i] = b
    M_jack[i] = m
end

In [39]:
@assert 2+2==5

LoadError: AssertionError: 2 + 2 == 5

In [40]:
M_jack

16-element Vector{Float64}:
 2.232537984491417
 2.3921175475773326
 2.2605682106945055
 2.187498406804059
 2.22443147433105
 2.2465180068300468
 2.2416049305577843
 2.2722484599220145
 2.238233179261636
 2.2122234573446833
 2.240129979429172
 2.2380920217881353
 2.2442548163988443
 2.2536918375457953
 2.204787636626191
 2.2326658474844585

In [41]:
f = Figure()
Axis(f[1, 1])
errorbars!(data.x, data.y, data.sigma_y)
scatter!(data.x, data.y, markersize = 10, color = :black)
for i in 1:n
    lines!(xx, B_jack[i] .+ M_jack[i] .* xx, color=:grey)
end
lines!(xx, b_opt .+ m_opt .* xx, color=:red, linewidth=3)
f

In [42]:
f = Figure()
Axis(f[1, 1])
scatter!(B_jack, M_jack)
f

In [43]:
using Statistics

In [45]:
m_jack = mean(M_jack)
b_jack = mean(B_jack)
b_jack, m_jack

(33.02960525252187, 2.2451002373179456)

In [46]:
sigma_m_jack = (n-1)/n * std(M_jack .- m_jack) # std can be taken here, in order to accurately do this you need a 
                                               # correction factor in (n-1)/n 

0.041620275377164465

In [47]:
sigma_b_jack = (n-1)/n * std(B_jack .- b_jack)

7.318438780103368

In [48]:
# another way to do that is to use Fischer information procedure to do some calculation
f = Figure(resolution=(800,500))
Axis(f[1, 1])
errorbars!(data.x, data.y, data.sigma_y)
scatter!(data.x, data.y, markersize = 10, color = :black)

lines!(xx, (b_jack .+ sigma_b_jack) .+ m_jack .* xx, color=:grey)
lines!(xx, (b_jack .- sigma_b_jack) .+ m_jack .* xx, color=:grey)
lines!(xx, b_jack .+ (m_jack .+ sigma_m_jack) .* xx, color=:grey)
lines!(xx, b_jack .+ (m_jack .- sigma_m_jack) .* xx, color=:grey)

lines!(xx, b_opt .+ m_opt .* xx, color=:red)#, linewidth=3)
f

# Outlier Methods

In [51]:
f = Figure()
Axis(f[1, 1])
errorbars!(alldata.x, alldata.y, alldata.sigma_y)
scatter!(data.x, data.y, markersize = 10, color = :red)
f

In [52]:
result = optimize(p -> objective_2(alldata.x, p[1], p[2], alldata.y, alldata.sigma_y),
                  [b,m] .+ 0.);
Optim.converged(result)

true

In [53]:
b_opt,m_opt = Optim.minimizer(result)

2-element Vector{Float64}:
 213.27260623234588
   1.0767505344575383

In [55]:
f = Figure()
Axis(f[1, 1])
errorbars!(alldata.x, alldata.y, alldata.sigma_y)
scatter!(alldata.x, alldata.y, markersize = 10, color = :black)
lines!(xx, b_opt .+ m_opt .* xx, )
f

In [59]:
# we are using local optimizer 

In [78]:
# function objective_outliers(parameters, x, y, sigma)
#     b = parameters[1]
#     m = parameters[2]
    
#     frac_bad = 0.01
#     like_bad = frac_bad*(1. ./600. )
    
#     y_pred = b .+ m .* x
    
#     like_good = (1. - frac_bad) .* 1 ./(sqrt(2.0 * π) .* sigma) * exp(-0.5 * (y .- y_pred)^2 ./ sigma.^2)
# #     loglike_good = log(1. - frac_bad) + -log.(sigma * sqrt(2*π)) - 0.5 .* (y .- y_pred).^2 ./ sigma.^2)
#     like = like_bad .+ like_good
    
#     loglike = log(like)
    
#     return -sum(loglike)
# end

function objective_outliers(parameters, x, y, sigma)
    b = parameters[1]
    m = parameters[2]

    frac_bad = 0.01
    like_bad = frac_bad * (1. / 600.)

    y_pred = b .+ m .* x
    like_good = (1. - frac_bad) * 1 ./(sqrt(2*π) .* sigma) .* exp.(-0.5 * (y .- y_pred).^2 ./ sigma.^2)
    like = like_bad .+ like_good
    loglike = log.(like)

    return -sum(loglike)
end

objective_outliers (generic function with 1 method)

In [74]:
# starting_param = [b_eye, m_eye]
result = optimize(p -> objective_outliers( b_jack, m_jack, alldata.x, alldata.y, alldata.sigma_y),
                  [b,m] .+ 0.);
Optim.converged(result)
b_punk, m_punk = Optim.minimizer(result)

LoadError: MethodError: no method matching objective_outliers(::Float64, ::Float64, ::Vector{Int64}, ::Vector{Int64}, ::Vector{Int64})
Closest candidates are:
  objective_outliers(::Any, ::Any, ::Any, ::Any) at In[73]:1

In [77]:
starting_params = [700 + 0., -0.5]
result = optimize(p -> objective_outliers(p, alldata.x, alldata.y, alldata.sigma_y),
                  starting_params)
@assert Optim.converged(result)
b_punk, m_punk = Optim.minimizer(result)

2-element Vector{Float64}:
 627.9728284643311
  -0.7590088958472745

In [79]:

f = Figure()
Axis(f[1, 1])
errorbars!(alldata.x, alldata.y, alldata.sigma_y)
scatter!(alldata.x, alldata.y, markersize=20, color=:red)

# yy_bad = xx .* m_bad .+ b_bad
# lines!(xx, yy_bad, color=:purple, linewidth=3)

yy_out = xx .* m_out .+ b_out
lines!(xx, yy_out, color=:green, linewidth=3)

yy_punk = xx .* m_punk .+ b_punk
lines!(xx, yy_punk, color=:blue, linewidth=3)

f

LoadError: UndefVarError: m_bad not defined