# First Julia Code

In [2]:
using Pkg
Pkg.add("WGLMakie")

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed Calculus ──────────────────── v0.5.1
   Installed JpegTurbo_jll ─────────────── v2.1.2+0
   Installed x265_jll ──────────────────── v3.5.0+0
   Installed libfdk_aac_jll ────────────── v2.0.2+0
   Installed ImageIO ───────────────────── v0.6.6
   Installed AxisArrays ────────────────── v0.4.6
   Installed TiffImages ────────────────── v0.6.3
   Installed Libmount_jll ──────────────── v2.35.0+0
   Installed JpegTurbo ─────────────────── v0.1.1
   Installed HypergeometricFunctions ───── v0.3.11
   Installed LERC_jll ──────────────────── v3.0.0+1
   Installed WGLMakie ──────────────────── v0.8.5
   Installed PNGFiles ──────────────────── v0.3.17
   Installed StatsFuns ─────────────────── v1.1.1
   Installed FFTW ──────────────────────── v1.5.0
   Installed ImageMagick ───────────────── v1.2.1
   Installed LoggingExtras ─────────────── v1.0.0
   Installed Opus_jll ──────────────────── v

In [1]:
using WGLMakie

In [2]:
f = Figure()
Axis(f[1,1])

xs = LinRange(0,10,100)
ys = LinRange(0,15,100)
zs = [cos(x)*sin(y) for x in xs, y in ys]

contourf!(xs,ys,zs)

f

# Introduction to Julia

In [3]:
println("Hello World")

Hello World


In [4]:
typeof(4.0)

Float64

In [5]:
typeof(1//4)

Rational{Int64}

In [8]:
typeof(3+ 3im)

Complex{Int64}

In [9]:
?abs

search: abs abs2 abspath abstract Absolute Absorption AbstractSet



```
abs(x)
```

The absolute value of `x`.

When `abs` is applied to signed integers, overflow may occur, resulting in the return of a negative value. This overflow occurs only when `abs` is applied to the minimum representable value of a signed integer. That is, when `x == typemin(typeof(x))`, `abs(x) == x < 0`, not `-x` as might be expected.

See also: [`abs2`](@ref), [`unsigned`](@ref), [`sign`](@ref).

# Examples

```jldoctest
julia> abs(-3)
3

julia> abs(1 + im)
1.4142135623730951

julia> abs(typemin(Int64))
-9223372036854775808
```


In [10]:
"hello "^2 

"hello hello "

In [11]:
a = [1, 2.0, "vhoufwf"]

3-element Vector{Any}:
 1
 2.0
  "vhoufwf"

In [12]:
fill(4.0,2,3)

2×3 Matrix{Float64}:
 4.0  4.0  4.0
 4.0  4.0  4.0

In [14]:
[row+col for row in 1:2, col in 1:3]

2×3 Matrix{Int64}:
 2  3  4
 3  4  5

In [24]:
a = LinRange(0,1,10);
println(a[1:2:5])
print(a[end])

LinRange{Float64}(0.0, 0.4444444444444444, 3)
1.0

### If function modifies it arguments then the convention is to put exclamation at the end

In [29]:
aa = append!([1,222],[1,2,3])

5-element Vector{Int64}:
   1
 222
   1
   2
   3

In [30]:
pop!(aa)

3

In [31]:
for i in aa
    println(i+10)
end

11
232
11
12


In [32]:
a = ones(10)'

10-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [41]:
zeros(10)

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

### Functions in Julia

$ sign evaluates the thing after that

In [43]:
i = 10
println("$(i+1)")

11


In [45]:
function is_pythegorean_triple(i,j,k)
    return i^2+j^2==k^2
end

is_pythegorean_triple (generic function with 1 method)

In [59]:
function list_pythegorean_triple(n)
    count = 0
    for i in 1:n, j in 1:n, k in 1:n
        if is_pythegorean_triple(i,j,k)
#             println("$i, $j, $k")
            count += 1
        end
    end
    return count
end

list_pythegorean_triple (generic function with 1 method)

In [60]:
list_pythegorean_triple(100)

104

### function is compiled when it is being called


In [62]:
@code_native is_pythegorean_triple(1,2,3)

	.text
	.file	"is_pythegorean_triple"
	.globl	julia_is_pythegorean_triple_13041 # -- Begin function julia_is_pythegorean_triple_13041
	.p2align	4, 0x90
	.type	julia_is_pythegorean_triple_13041,@function
julia_is_pythegorean_triple_13041:      # @julia_is_pythegorean_triple_13041
; ┌ @ In[45]:1 within `is_pythegorean_triple`
	.cfi_startproc
# %bb.0:                                # %top
; │ @ In[45]:2 within `is_pythegorean_triple`
; │┌ @ intfuncs.jl:321 within `literal_pow`
; ││┌ @ int.jl:88 within `*`
	imulq	%rdi, %rdi
	imulq	%rsi, %rsi
; │└└
; │┌ @ int.jl:87 within `+`
	addq	%rdi, %rsi
; │└
; │┌ @ intfuncs.jl:321 within `literal_pow`
; ││┌ @ int.jl:88 within `*`
	imulq	%rdx, %rdx
; │└└
; │┌ @ promotion.jl:477 within `==`
	cmpq	%rdx, %rsi
	sete	%al
; │└
	retq
.Lfunc_end0:
	.size	julia_is_pythegorean_triple_13041, .Lfunc_end0-julia_is_pythegorean_triple_13041
	.cfi_endproc
; └
                                        # -- End function
	.section	".note.GNU-stack","",@progbits


In [68]:
function addd(a)
    for i in 1:length(a)
        a[i]+=10
    end
end

addd (generic function with 1 method)

In [69]:
a = [1,2,3]
addd(a)
a

3-element Vector{Int64}:
 11
 12
 13

# visulisation

 ]  is needed to address the package manager in julia

In [81]:
f = Figure()
Axis(f[1,1])
xs = LinRange(0, π, 100)
ys = sin.(xs)

linesegments!(xs,ys)
f

Plan for today:
- defining types in Julia
- defining packages in Julia

## Types

In [4]:
# function translate(x,y ,dx,dy)
struct IntPoint # structure/types start with upper case letter
    x::Int
    y::Int
end

In [9]:
p = IntPoint(1,2)

IntPoint(1, 2)

In [10]:
typeof(p)

IntPoint

In [11]:
p.x

1

In [12]:
struct FloatPoint
    x::Float64
    y::Float64
end
q = FloatPoint(1.0,2)

FloatPoint(1.0, 2.0)

## Generica types

In [2]:
struct Point{T} # T is unspecified type  just stored in very little probably 2 bit cpu space
    x::T
    y::T
end

In [14]:
Point{Int}(1,2)

Point{Int64}(1, 2)

In [3]:
p = Point{Int64}(1,2)
q = Point{Int64}(-1,2)
p.x

1

In [17]:
function add(p::Point, q::Point)
    x = p.x+q.x
    y = p.y+q.y
    return Point(x,y)
end

add (generic function with 1 method)

In [23]:
print(add(p,q))

Point{Int64}(0, 4)

In [25]:
supertype(Point{Int})

Any

## Function Overloading

In [26]:
+(2,3) # function name is actually +

5

In [4]:
function Base.:+(p::Point, q::Point)
    x = p.x+q.x
    y = p.y+q.y
    return Point(x,y)
end

In [28]:
p+q

Point{Int64}(0, 4)

In [29]:
?Base

search: Base basename PointBased AbstractSet AbstractScene broadcast_foreach



```
Base
```

The base library of Julia. `Base` is a module that contains basic functionality (the contents of `base/`). All modules implicitly contain `using Base`, since this is needed in the vast majority of cases.


In [ ]:
Base.:+(x::Int, y::Int) = x+y # must not do it for the base part

StackOverflowError: SYSTEM: show(lasterr) caused an error

Careful about the namespace 

# Mutable Struct 

In [6]:
mutable struct MPoint{T} # heap, grabage collector, like python , pass the pointer 
    x::T
    y::T
end

In [7]:
p = MPoint(2,3)

MPoint{Int64}(2, 3)

In [8]:
p.x=10

10

# Dual Numbers

Complex: a + i b

- two-vector of real numbers
- can add complex numbers and multiply two numbers

Define: i^2 := -1

(a + ib)(c + id) = ac+ ibc + iad + i^2 bd
                 = ac+ ibc + iad - bd
            
- can multiply complex numbers
- can divide (inverse of multiplication)

Dual Numbers: a + ϵ b

Define: ϵ^2 := 0

In [9]:
ϵ = 10

10

In [10]:
println(ϵ)

10


# A package for the dual numbers

In [11]:
]generate DualNumbers

  Generating  project DualNumbers:
    DualNumbers/Project.toml
    DualNumbers/src/DualNumbers.jl


In [12]:
]add Revise

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed CodeTracking ───── v1.2.0
   Installed JuliaInterpreter ─ v0.9.20
   Installed LoweredCodeUtils ─ v2.3.0
   Installed Revise ─────────── v3.5.0
    Updating `~/.julia/environments/v1.8/Project.toml`
  [295af30f] + Revise v3.5.0
    Updating `~/.julia/environments/v1.8/Manifest.toml`
  [da1fd8a2] + CodeTracking v1.2.0
  [aa1ae85d] + JuliaInterpreter v0.9.20
  [6f1432cf] + LoweredCodeUtils v2.3.0
  [295af30f] + Revise v3.5.0
Precompiling project...
  ✓ CodeTracking
  ✓ JuliaInterpreter
  ✓ LoweredCodeUtils
  ✓ Revise
  4 dependencies successfully precompiled in 21 seconds. 214 already precompiled.


When ever you use the package use to revise package so that your package got updated; and the real thing is going to be updated automatically

In [13]:
using Revise

In [18]:
]activate DualNumbers

  Activating project at `~/numerical/DualNumbers`


In [26]:
using DualNumbers

In [22]:
? Dual

search: Dual DualNumbers MethodSummary



```
Dual: A dual number defintion inside a package
```


In [24]:
x = Dual(1,2)
y = Dual(2,3)

Dual{Int64}(2, 3)

In [27]:
x + y

Dual{Int64}(3, 5)

In [28]:
x - y

Dual{Int64}(-1, -1)

- Make a directory name "test" inside the DualNumbers directory
- The name needed to be test for testing purpose
- You need to create a file named "runtests.jl"
- The name need to be exact
- @test is a macro evaluated provided by the test package

In [30]:
]add Test

   Resolving package versions...
    Updating `~/numerical/DualNumbers/Project.toml`
  [8dfed614] + Test
    Updating `~/numerical/DualNumbers/Manifest.toml`
  [2a0f44e3] + Base64
  [b77e0a4c] + InteractiveUtils
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [8dfed614] + Test
Precompiling project...
  ✓ DualNumbers
  1 dependency successfully precompiled in 0 seconds
  1 dependency precompiled but a different version is currently loaded. Restart julia to access the new version


In [32]:
]test

     Testing DualNumbers
      Status `/tmp/jl_LhUsZ6/Project.toml`
  [84cc2a82] DualNumbers v0.1.0 `~/numerical/DualNumbers`
  [8dfed614] Test `@stdlib/Test`
      Status `/tmp/jl_LhUsZ6/Manifest.toml`
  [84cc2a82] DualNumbers v0.1.0 `~/numerical/DualNumbers`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA v0.7.0 `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [8dfed614] Test `@stdlib/Test`
     Testing Running tests...
     Testing DualNumbers tests passed 


### Monday tutorial: Readme, adding dual numbers and multiplying and dividing the dual numbers and expand the test 
### Automate the test cases run by Github

Functions can be called in any order in src/:project_name:.jl file