# Linear Algebra

## Vector and Matrics

In [1]:
using LinearAlgebra

In [2]:
# defintition of vectors
x = zeros(4)#zeros(4,4)#[1 2; 3 4] #randn(4) #fill(89, 3)
#x + I

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [3]:
typeof(I) # this is overloaded using the Linear Algebra

UniformScaling{Bool}

In [4]:
x' # traspose(x) would also work here

1×4 adjoint(::Vector{Float64}) with eltype Float64:
 0.0  0.0  0.0  0.0

In [5]:
typeof(x')

Adjoint{Float64, Vector{Float64}}

In [6]:
typeof(x'')

Vector{Float64} (alias for Array{Float64, 1})

In [7]:
# three dimensional matrix
M = [1;2;; 3;4;;; 5;6;; 7;8]

2×2×2 Array{Int64, 3}:
[:, :, 1] =
 1  3
 2  4

[:, :, 2] =
 5  7
 6  8

In [8]:
reshape(M,(4,2))

4×2 Matrix{Int64}:
 1  5
 2  6
 3  7
 4  8

In [9]:
reshape(M,(2,4)) # interpret as a single vector M as a list then reshape it

2×4 Matrix{Int64}:
 1  3  5  7
 2  4  6  8

# Matrix types

- dense (full)
- symmetric
- triangular matrices
- diagonal (storage are efficient if you define it such)
- bi- diagonal or tri- diagonal (100 times or million times faster)
- sparse matrix (most of the entries are zeros)


In [10]:
A = rand(10,10)

10×10 Matrix{Float64}:
 0.942077   0.965691  0.88784   0.562646  …  0.528765   0.0878948  0.767142
 0.784175   0.377635  0.689395  0.584388     0.539022   0.590604   0.890042
 0.77213    0.915486  0.409364  0.475208     0.398243   0.705265   0.955288
 0.310156   0.874472  0.95764   0.23677      0.476028   0.331062   0.420232
 0.237703   0.594002  0.872162  0.239734     0.568534   0.259815   0.979641
 0.564198   0.66327   0.420455  0.905859  …  0.554669   0.811955   0.23485
 0.983523   0.106797  0.754497  0.114469     0.707223   0.490961   0.576462
 0.359889   0.640381  0.538785  0.093185     0.624472   0.966792   0.633796
 0.826241   0.04384   0.987872  0.56373      0.0951485  0.382618   0.0677745
 0.0731436  0.327925  0.547843  0.119314     0.879223   0.676977   0.260016

In [11]:
Symmetric(A) # -A would give that upper triangular matrices zer0

10×10 Symmetric{Float64, Matrix{Float64}}:
 0.942077   0.965691  0.88784   0.562646   …  0.528765  0.0878948  0.767142
 0.965691   0.377635  0.689395  0.584388      0.539022  0.590604   0.890042
 0.88784    0.689395  0.409364  0.475208      0.398243  0.705265   0.955288
 0.562646   0.584388  0.475208  0.23677       0.476028  0.331062   0.420232
 0.305006   0.708606  0.765528  0.518956      0.568534  0.259815   0.979641
 0.635814   0.275007  0.24791   0.471199   …  0.554669  0.811955   0.23485
 0.102553   0.144136  0.334147  0.0770773     0.707223  0.490961   0.576462
 0.528765   0.539022  0.398243  0.476028      0.624472  0.966792   0.633796
 0.0878948  0.590604  0.705265  0.331062      0.966792  0.382618   0.0677745
 0.767142   0.890042  0.955288  0.420232      0.633796  0.0677745  0.260016

In [12]:
Symmetric(A+A') # this is going to change the type

10×10 Symmetric{Float64, Matrix{Float64}}:
 1.88415   1.74987   1.65997   0.872802  …  0.888654  0.914136  0.840286
 1.74987   0.755269  1.60488   1.45886      1.1794    0.634444  1.21797
 1.65997   1.60488   0.818729  1.43285      0.937029  1.69314   1.50313
 0.872802  1.45886   1.43285   0.473541     0.569213  0.894792  0.539546
 0.542709  1.30261   1.63769   0.75869      0.730592  1.04545   1.56604
 1.20001   0.938278  0.668365  1.37706   …  0.87072   1.12074   0.643727
 1.08608   0.250933  1.08864   0.191546     1.06207   0.828628  1.34027
 0.888654  1.1794    0.937029  0.569213     1.24894   1.06194   1.51302
 0.914136  0.634444  1.69314   0.894792     1.06194   0.765236  0.744752
 0.840286  1.21797   1.50313   0.539546     1.51302   0.744752  0.520032

In [13]:
Diagonal(rand(5))

5×5 Diagonal{Float64, Vector{Float64}}:
 0.848609   ⋅         ⋅         ⋅          ⋅ 
  ⋅        0.577059   ⋅         ⋅          ⋅ 
  ⋅         ⋅        0.142162   ⋅          ⋅ 
  ⋅         ⋅         ⋅        0.0984814   ⋅ 
  ⋅         ⋅         ⋅         ⋅         0.399892

## Operations on matrices

In [14]:
inv(A) * A == I

false

In [15]:
inv(A)

10×10 Matrix{Float64}:
  1.83945     2.4834     2.26496   …  -1.14112    1.28938    3.92509
  0.905832    0.218814   1.52729      -0.525314   0.324757   1.75763
  0.285651    0.449169  -0.488956      0.417591   0.935421   0.44757
 -0.0896868  -1.0245    -1.97075       0.788957  -0.477931  -2.41318
 -0.996805    0.555237   1.04384      -1.43703   -0.179908   0.503118
 -2.71356    -5.50391   -3.37839   …   1.97754   -2.31367   -7.86533
  0.483031   -2.19791    0.213012      0.522134   0.65308   -0.0879706
  2.09538     4.65888    1.33789      -1.93119    0.300064   5.96
 -1.19957    -0.673046  -0.627443      1.47643   -0.154145  -1.77322
 -1.08653    -1.59292   -1.18645       1.02516   -1.01163   -3.35504

In [16]:
B = big.(rand(-199:100, 5,5)) // 100

5×5 Matrix{Rational{BigInt}}:
  -89//50   -177//100     1//4    -177//100  -18//25
   39//100   -29//20    -36//25     -7//100    3//4
   97//100    73//100   -18//25      9//25    17//50
 -147//100   -77//100  -189//100     3//50   -31//20
 -151//100   -53//100   -11//20    -91//50    17//100

In [17]:
inv(B)*B == I

true

## Floating point numbers

- internal representation: m * 2^e

- double precision 64 bits: m as 53 bits, e as 11 bits

- single precision 32 bits

- half precision 16 bits

- 8 bits


ẋ , x̄, x̃

In [18]:
isapprox(inv(A)*A, I) 

true

In [19]:
inv(A) * A ≈ I # use \approx to create the symbol after pressing tab ≈ 

true

In [20]:
Rational(0.1)

3602879701896397//36028797018963968

In [21]:
float(Rational(0.1)-1//10)

5.551115123125783e-18

In [22]:
BigFloat(π) # Float64

3.141592653589793238462643383279502884197169399375105820974944592307816406286198

In [23]:
isapprox(1,1.0001; atol=1e-3)

true

In [24]:
2 \ 3

1.5

In [25]:
A = rand(10,10)
b = randn(10)
x = A \ b # use this under operator

10-element Vector{Float64}:
   9.786137015012152
   2.1067101105236485
  -2.246868985965882
 -13.455025181307148
   6.8168468547306045
   4.264424925531804
  -3.0650562437789493
   7.523814324177959
  -4.430582758732867
  -5.457030724828215

In [26]:
A *x ≈ b

true

# Least Squares

In [27]:
# expansion coefficents
pmax = 4

4

In [49]:
#evaluation point
npoints = 11
x = LinRange(0, 2*π, npoints)

11-element LinRange{Float64, Int64}:
 0.0,0.628319,1.25664,1.88496,2.51327,…,4.39823,5.02655,5.65487,6.28319

In [50]:
# target function
f(x) = sin(x)

f (generic function with 2 methods)

In [51]:
# matrix
A = [x[i]^p for i in 1:npoints, p in 0:pmax]

11×5 Matrix{Float64}:
 1.0  0.0        0.0         0.0         0.0
 1.0  0.628319   0.394784    0.24805     0.155855
 1.0  1.25664    1.57914     1.9844      2.49367
 1.0  1.88496    3.55306     6.69736    12.6242
 1.0  2.51327    6.31655    15.8752     39.8988
 1.0  3.14159    9.8696     31.0063     97.4091
 1.0  3.76991   14.2122     53.5788    201.987
 1.0  4.39823   19.3444     85.0812    374.207
 1.0  5.02655   25.2662    127.002     638.38
 1.0  5.65487   31.9775    180.829    1022.56
 1.0  6.28319   39.4784    248.05     1558.55

In [52]:
fstart(x) = sin(x)
b = fstart.(x)

11-element Vector{Float64}:
  0.0
  0.5877852522924731
  0.9510565162951535
  0.9510565162951536
  0.5877852522924732
  1.2246467991473532e-16
 -0.587785252292473
 -0.9510565162951535
 -0.9510565162951536
 -0.5877852522924734
 -2.4492935982947064e-16

In [53]:
c = (A'*A) \ (A' * b)

5-element Vector{Float64}:
 -0.06350896223836319
  1.7067771322018093
 -0.8052738471997284
  0.08544220888303738
 -8.360349981092898e-15

In [54]:
f(c, x) = sum(c[p+1]* x^p for p in 0:pmax)

f (generic function with 2 methods)

In [38]:
using WGLMakie

In [56]:
fig = Figure()
Axis(fig[1,1])
xx = LinRange(0, 2*π, 201)
yy = [f(c,x) for x in xx]
lines!(xx,fstart.(xx))
lines!(xx, yy)
scatter!(x, [f(c,x′) for x′ in x])
fig

In [59]:
fig = Figure()
Axis(fig[1,1])
xx = LinRange(0, 2*π, 201)
yy = [f(c,x) - fstart.(x) for x in xx]
lines!(xx, yy)
fig

## Matrix Operation

- LU Decomposition
- A = L*U

In [60]:
A = randn(4,4);

In [68]:
# permutation is needed to be accounted for
Low = lu(A).L;
Upp = lu(A).U;

In [64]:
Low * Upp ≈ A

false

- QR decomposition
- A = Q * R
- Q is orthogonal matrix, right triangular matrix

In [65]:
q = qr(A).Q
r = qr(A).R;

In [67]:
q * r ≈ A

true

# Linear Operators and Matrics

In [69]:
using SparseArrays

In [70]:
A = sprandn(10, 10, 1/10)

10×10 SparseMatrixCSC{Float64, Int64} with 10 stored entries:
  ⋅    ⋅    ⋅        ⋅     ⋅         ⋅       …   ⋅          ⋅         ⋅ 
  ⋅    ⋅    ⋅        ⋅     ⋅         ⋅           ⋅          ⋅         ⋅ 
  ⋅    ⋅   1.34123   ⋅     ⋅         ⋅           ⋅          ⋅         ⋅ 
  ⋅    ⋅    ⋅        ⋅     ⋅         ⋅           ⋅          ⋅         ⋅ 
  ⋅    ⋅    ⋅        ⋅   -0.205012   ⋅           ⋅          ⋅         ⋅ 
  ⋅    ⋅    ⋅        ⋅     ⋅         ⋅       …   ⋅          ⋅         ⋅ 
  ⋅    ⋅    ⋅        ⋅   -0.572688   ⋅          1.27386   -1.01286    ⋅ 
  ⋅    ⋅    ⋅        ⋅     ⋅        1.60425      ⋅          ⋅         ⋅ 
  ⋅    ⋅    ⋅        ⋅     ⋅         ⋅           ⋅          ⋅         ⋅ 
  ⋅    ⋅    ⋅        ⋅     ⋅         ⋅          0.418653  -0.868269  0.330927

In [72]:
eigvals(Matrix(A)) # don't do this is server, because it is inefficients
# applying matrix iteratively to find for the eigenvalues and matrices

10-element Vector{ComplexF64}:
 -0.37419912999134014 - 0.6481319052930721im
 -0.37419912999134014 + 0.6481319052930721im
 -0.20501212260439255 + 0.0im
                  0.0 + 0.0im
                  0.0 + 0.0im
                  0.0 + 0.0im
                  0.0 + 0.0im
   0.3309271351193155 + 0.0im
   0.7483982599826804 + 0.0im
    1.341232689340303 + 0.0im

In [73]:
]add Arpack # Arnoldi iterations for real symmetric 

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed Arpack_jll ─ v3.5.1+1
   Installed Arpack ───── v0.5.4
    Updating `~/.julia/environments/v1.8/Project.toml`
  [7d9fca2a] + Arpack v0.5.4
    Updating `~/.julia/environments/v1.8/Manifest.toml`
  [7d9fca2a] + Arpack v0.5.4
⌅ [68821587] + Arpack_jll v3.5.1+1
        Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
Precompiling project...
  ✓ Arpack_jll
  ✓ Arpack
  2 dependencies successfully precompiled in 9 seconds. 273 already precompiled.


In [74]:
using Arpack

In [75]:
eigs(A; nev=4)

(ComplexF64[1.341232689340303 + 0.0im, -0.37419912999134075 + 0.648131905293072im, -0.37419912999134075 - 0.648131905293072im, 0.74839825998268 + 0.0im], ComplexF64[1.0579669388862433e-17 + 0.0im 8.849811101580706e-19 - 5.39160531624513e-17im 8.849811101580706e-19 + 5.39160531624513e-17im -3.300309642335504e-17 + 0.0im; 1.4370204648353316e-20 + 0.0im 5.338929410713101e-22 - 1.161552850753584e-19im 5.338929410713101e-22 + 1.161552850753584e-19im -6.812740647847932e-20 + 0.0im; … ; 1.2221620914872766e-17 + 0.0im -9.107767336865035e-18 - 3.812467350785373e-17im -9.107767336865035e-18 + 3.812467350785373e-17im -3.9851059320574117e-17 + 0.0im; 7.412551671379199e-17 + 0.0im 0.0311178185986144 + 0.20834432991714685im 0.0311178185986144 - 0.20834432991714685im -0.4431721826057228 + 0.0im], 4, 1, 10, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])